version: "3"
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: ticketify_db

  django:
    hostname: django
    env_file:
      - stack.env
    build:
      context: ./
      dockerfile: docker/prod/django/Dockerfile
    ports:
      - "8443:8443"
    depends_on:
      - db
      - redis
    container_name: ticketify_django

  nodejs_v1:
    hostname: nodejs_v1
    build:
      context: ./
      dockerfile: docker/prod/nodejs_v1/Dockerfile
      args:
        - NODE_ENV=staging
    environment:
        ANGULAR_ENV: staging 
    ports:
      - "4200:4200"
      - "3000:3000"
    volumes:
    - /code/node_modules
    container_name: ticketify_nodejs_v1

  redis:
    image: redis:7.2-rc3
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./
      dockerfile: docker/prod/celery/Dockerfile
    env_file:
      - stack.env
    depends_on:
      - db
      - redis
      - django
