version: "3"
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    container_name: ticketify_db

  redis:
    image: redis:7.2-rc3
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    expose:
      - "6379"

networks:
  default:
    external: true
    name: scoobydoo