# Generated by Django 4.2.3 on 2023-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('paytm', 'Paytm')], max_length=100, null=True),
        ),
    ]
