# Generated by Django 4.2.3 on 2023-09-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_subevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('billdesk', 'Billdesk')], max_length=100, null=True),
        ),
    ]
