# Generated by Django 4.2.3 on 2023-09-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_subevent_coordinator_subevent_coordinator_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='terms_url',
            field=models.URLField(blank=True),
        ),
    ]
