# Generated by Django 4.2.3 on 2023-09-20 16:21

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_flagship_event_included_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='email_sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocode',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(default=event.models.generate_id, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
