# Generated by Django 4.2.3 on 2023-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_promocode_email_promocode_email_sended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rules_url',
            field=models.URLField(blank=True),
        ),
    ]
