# Generated by Django 4.2.3 on 2023-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_rules_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='student_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
