# Generated by Django 4.2.3 on 2023-10-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_student_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
