# Generated by Django 4.2.3 on 2023-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_sponsor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maintaince_mode',
            field=models.BooleanField(default=False),
        ),
    ]
