# Generated by Django 4.2.3 on 2024-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_maintaince_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_template',
            field=models.CharField(choices=[('sabrang', 'SABRANG'), ('testing', 'TESTING')], default='testing', max_length=100),
        ),
    ]
