# Generated by Django 4.2.3 on 2023-08-13 16:53

from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(default=ticket.models.generate_id, editable=False, max_length=7, primary_key=True, serialize=False)),
                ('check_in', models.CharField(editable=False, max_length=10, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_image_generated', models.BooleanField(default=False)),
                ('ticket_image', models.ImageField(blank=True, null=True, upload_to='ticket_images')),
                ('order_id', models.CharField(default='', max_length=100, null=True, unique=True)),
                ('referral', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('selected_addons', models.ManyToManyField(blank=True, to='event.addon')),
                ('selected_sub_events', models.ManyToManyField(blank=True, to='event.subevent')),
                ('transaction_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent_time', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_email_logs', to='ticket.ticket')),
            ],
            options={
                'db_table': 'ticket_email_log',
                'ordering': ['-email_sent_time'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(choices=[('QR', 'QR Code'), ('MANUAL', 'Manual')], default='QR', max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_check_in', to='ticket.ticket')),
            ],
            options={
                'db_table': 'check_in',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
