# Generated by Django 4.2.3 on 2023-09-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('STUDENT', 'Student')], default='REGULAR', max_length=100),
        ),
    ]
