# Generated by Django 4.2.3 on 2023-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='promo_applied',
            field=models.BooleanField(default=False),
        ),
    ]
