# Generated by Django 4.2.3 on 2023-08-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_mail_log',
        ),
    ]
