# Generated by Django 4.2.3 on 2023-08-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_ticket_mail_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_image_location',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_images'),
        ),
    ]
