# Generated by Django 4.2.3 on 2023-09-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='college_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College')], default='COLLEGE', max_length=100),
        ),
    ]
