# Generated by Django 4.2.3 on 2023-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_college_name_ticket_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='verification_id',
            field=models.ImageField(blank=True, null=True, upload_to='verification_images'),
        ),
    ]
