# Generated by Django 4.2.3 on 2023-10-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticket_id_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
