# Generated by Django 4.2.3 on 2023-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('order_id', models.CharField(default='', max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_currency', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook_recieved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-id'],
            },
        ),
    ]
